name: CI/CD

on:
  pull_request:
    branches: ["*"]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.1.4"

      - name: Cache Terraform modules
        uses: actions/cache@v4
        with:
          path: .terraform/
          key: terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: terraform-

      - run: terraform init
      - run: terraform fmt -check
      - run: terraform validate -no-color

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: npm install
      - run: echo testPass

  release:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'

      - name: Copy releaserc config
        run: cp .github/.releaserc.yml .

      - name: Install dependencies
        run: npm install

      - name: Install semantic-release globally
        run: npm i -g semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/npm @semantic-release/github

      - name: Run semantic-release
        run: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
