name: Build & Release
on:
  push:
    branches:
      - cicd/auto-release
jobs:
  generate_version:
    runs-on: ubuntu-latest
    name: Generate release version and tag
    outputs:
      nextVersion: ${{ steps.semver.outputs.nextVersion }}
      oldVersion: ${{ steps.semver.outputs.oldVersion }}
      prerelease: ${{ steps.semver.outputs.prerelease }}
    steps:
      - name: Magic Semver Action
        id: semver
        uses: mehdi-ra/semversion@v0.1.2
        with:
          dev_branch_name: "cicd/auto-release"

  create_github_release:
    runs-on: ubuntu-latest
    needs: [generate_version]
    permissions:
      contents: write
    if: needs.generate_version.outputs.oldVersion != needs.generate_version.outputs.nextVersion
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          fromTag: ${{ needs.generate_version.outputs.oldVersion }}
          toTag: ${{ needs.generate_version.outputs.nextVersion }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: softprops/action-gh-release@v1
        with:
          name: ${{ needs.generate_version.outputs.nextVersion }}
          tag_name: '${{ needs.generate_version.outputs.nextVersion }}'
          body: ${{ steps.changelog.outputs.changelog }}
          prerelease: '${{ needs.generate_version.outputs.prerelease }}'
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
